using System.Net.Http.Json;

namespace Fireblocks.Api.Tests;

public class TokenServiceTests : BaseServiceTests
{
	private readonly ITokenService _tokenService;

	public TokenServiceTests(ITestOutputHelper testOutputHelper) : base(testOutputHelper) =>
		_tokenService = new TokenService(FireblocksApiConfig, JwtConfig);

	[Fact]
	public void BuildToken_ShouldSucceed()
	{
		// Given
		var requestMessgage = new HttpRequestMessage(HttpMethod.Get, $"{FireblocksApiConfig.BaseUrl}/v1/vault/accounts");
		var token = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmkiOiIvdjEvdmF1bHQvYWNjb3VudHMiLCJub25jZSI6IkQzRDJEMkg3UklLQUwiLCJpYXQiOjE2NjUzNjAwMDAsImV4cCI6MTY2NTM2MDAyNSwic3ViIjoiVGVzdEFwaUtleSIsImJvZHlIYXNoIjoiMTJhZTMyY2IxZWMwMmQwMWVkYTM1ODFiMTI3YzFmZWUzYjBkYzUzNTcyZWQ2YmFmMjM5NzIxYTAzZDgyZTEyNiJ9.sgHqqv90JToko72YYqArAZG3Bs4WHJ4m_mxpXi_HkIissN-BYfI97D2z7uvVGR1voCZaV8lZ6Tr37uLOSIXjXA_iF5l4q4pKBnXcNwiwMjqrrXdKC9LNoTkKsUEKByH3f7kdsSBqfXG7Vuh8b9dsvuK572WUAsUWlrQa38QNA5SHUJUfqnesH9EEIhJ0k_xC7ATt-Q6MxG8CZZXu78DL4r8Ip09TZi_Weh1qnX3fTmlUGzqGlrVpEcooWXIcJMNyS852Dk6K2uWJOS5HSY2DOdYb9gc6xuKAm1JLHyAVMfQ6uGDwwqYUYboBh4iaHULVk1nAwfALlVuhvCaBPvg9ESwMbpp7XHDROcKOVxuxfWU4vy4m7tObdDaSrsbGSfwxMxnBK96GxfQsY30rXXey3xrBQFV6P0oFGTIlnXNepwQ1l26Oww-m0qQUp5By15lsMWBjrjgmugxkL8V3WeLwJCUxH5GzpU9RewDAL2EKSeE15_9PAWqnsqop1TjtjqhP7vu3lt5rZ1OnmIdB40EHyISk4seMEq4XAeLp11XC0x07_7BVAHib9CUNEyM4_Sa3s9tN60Sur_EYbF7-qIeXQP9Vu60D8ggiWFzssEsV7m4Isvtac9R9CvCh2ufei4lWM11qmczI_89EAj4SYYlHTxm693F4kSXaFvTNj71OFcQ";

		// When
		var result = _tokenService.BuildToken(requestMessgage);

		// Then
		Assert.Equal(token, result);
	}

	[Fact]
	public void BuildToken_WithRequestBody_ShouldSucceed()
	{
		// Given
		var requestMessgage = new HttpRequestMessage(HttpMethod.Get, $"{FireblocksApiConfig.BaseUrl}/v1/vault/accounts")
		{
			Content = JsonContent.Create(new { })
		};
		var token = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmkiOiIvdjEvdmF1bHQvYWNjb3VudHMiLCJub25jZSI6IkQzRDJEMkg3UklLQUwiLCJpYXQiOjE2NjUzNjAwMDAsImV4cCI6MTY2NTM2MDAyNSwic3ViIjoiVGVzdEFwaUtleSIsImJvZHlIYXNoIjoiNDQxMzZmYTM1NWIzNjc4YTExNDZhZDE2ZjdlODY0OWU5NGZiNGZjMjFmZTc3ZTgzMTBjMDYwZjYxY2FhZmY4YSJ9.Y_30nCzINdUYj_pZPytB65EDbQi-2NKVwgMrB2VhfKmDDdrvmO6NGDKup-7TFE0w7FejQQGZyl8DrnNuO0O-hKycTBmfUJQqed4BnGhmDFAPYSFYdTNitoFbbB02bXh_cT-jfloiq2r8om2H5MnrvpGt78SP-p91FGbtgiIwq-wRyZRPoil8sp8viJvk6EDxezyokSmDb7ZxhDDNFQbRSlMPIdjD-d6RkshWu41f3B7_nObfFy1wfRgOac5iYUs2cvGEHe07P9oRNSf4ciwqMTX_6p9BC8D4qV2MWSe_uFKifPZIhBIitOHX-FDscNhQQMTI8EPf5PxYpGW61DzckPMHAJ4LAixRsIdhcPC0rpRyD9riIdl3jJX70kBdgoOpBhJbvlNtu6RSx3i0nik0Mgns45I2ZDXEo62PFhN39mvzkczxtbjBlhfllIzm8ykARf4OCmvBNWDRA3ycLdWy0vkb_UU2970RFJj7YuS-auBm7oXYu7tfvPHhyIqDSjWTggMNFPy3HRrqyvbnKEMCW0X_ED2tXEaRCvFGwikqZmdEN9cLsQKxTppobrrAkljfPuZe3939XA3jaP9-vPrIqcPArIhAiRWHsAGaz4I1LPz0LS_CZ9va7jmnZKkNxZmHprB1vU1xOS-cx1kIbhuWp-hKEO8Kg8puywdBoszVJ3I";

		// When
		var result = _tokenService.BuildToken(requestMessgage);

		// Then
		Assert.Equal(token, result);
	}
}
